package com.hhvvg.anydebug.util

import android.view.View

const val GITHUB_PAGE_URL = "https://github.com/gitofleonardo/AnyDebug"

const val APP_FIELD_SHOW_BOUNDS = "APP_FIELD_SHOW_BOUNDS"

const val APP_FIELD_FORCE_CLICKABLE = "APP_FIELD_FORCE_CLICKABLE"

const val DEFAULT_NOTIFICATION_CHANNEL_ID = "DEFAULT_NOTIFICATION_CHANNEL_ID"

const val APP_FIELD_GLOBAL_CONTROL_ENABLED = "APP_FIELD_GLOBAL_CONTROL_ENABLED"

const val APP_FIELD_PERSISTENT_ENABLE = "APP_FIELD_PERSISTENT_ENABLE"

const val ACTIVITY_FIELD_GLOBAL_ENABLE = "ACTIVITY_FIELD_GLOBAL_ENABLE"

val visibilityArray = arrayOf(
    View.VISIBLE,
    View.INVISIBLE,
    View.GONE
)