package com.hhvvg.anydebug.util

const val GITHUB_PAGE_URL = "https://github.com/gitofleonardo/AnyDebug"

const val APP_FIELD_SHOW_BOUNDS = "APP_FIELD_SHOW_BOUNDS"

const val APP_FIELD_FORCE_CLICKABLE = "APP_FIELD_FORCE_CLICKABLE"

const val APP_FIELD_GLOBAL_CONTROL_ENABLED = "APP_FIELD_GLOBAL_CONTROL_ENABLED"

const val APP_FIELD_PERSISTENT_ENABLE = "APP_FIELD_PERSISTENT_ENABLE"

const val APP_FIELD_PERSISTENT_RULES = "APP_FIELD_PERSISTENT_RULES"

const val APP_FIELD_PERSISTENT_RULES_MAP = "APP_FIELD_PERSISTENT_RULES_MAP"

const val APP_FIELD_LIFECYCLE_CALLBACK = "APP_FIELD_LIFECYCLE_CALLBACK"

const val APP_FIELD_CURRENT_ACTIVITY_REF = "APP_FIELD_CURRENT_ACTIVITY_REF"

const val ACTIVITY_FIELD_GLOBAL_ENABLE_RECEIVER = "ACTIVITY_FIELD_GLOBAL_ENABLE_RECEIVER"